### ISSUE TITLE
Evaluation error: newsplit: out of vertex space.

### ISSUE THREAD

**Issue by biopig** [bmansfeld/QTLseqR#10]
when i use my data analysis, and i meet the error
```
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Error in mutate_impl(.data, dots) : 
  Evaluation error: newsplit: out of vertex space.
besides: There were 50 or more warnings (use warnings() to see the first 50)
```

my code is 
```df_filt <- runGprimeAnalysis(SNPset = df_filt,windowSize = 1000,outlierFilter = "deltaSNP")```

**Comment by biopig** [comment]
i have send my file to you email     mansfeld@msu.edu

**Comment by bmansfeld** [comment]
Hi please see issue #9.
Your window is very small. I recommend increasing it to at least 1Mb.
Please read Magwene et al. on window size selection.
