### ISSUE TITLE
  runGprimeAnalysis 

### ISSUE THREAD

**Issue by wangyuu** [bmansfeld/QTLseqR#12]
when I   run runGprimeAnalysis command， I got an error ：
Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Using deltaSNP-index to filter outlier regions with a threshold of 0.1
Estimating the mode of a trimmed G prime set using the 'modeest' package...
Error in mutate_impl(.data, dots) :
  Evaluation error: non-numeric argument to mathematical function.

**Comment by bmansfeld** [comment]
Hi,
That seems like you have some non-integer/numeric value in one of the columns.
Check your column classes to see. 
How did you import that data? 
Ben

**Comment by wangyuu** [comment]
Thank you for your reply.
I imported my data using the command :
file <- "Apple.TwoPools.snp.table"
Chroms < c("Chr10","Chr11","Chr13","Chr12","Chr15","Chr14","Chr17","Chr16","Chr01","Chr00","Chr03","Chr02","Chr05","Chr04","Chr07","Chr06","Chr09","Chr08")
df <- importFromGATK (file = file, highBulk = HighBulk, lowBulk = LowBulk, chromList = Chroms)

It's weird that I can run this command "df_filt <- runQTLseqAnalysis (SNPset = df_filt, windowSize = 1e6, popStruc = "F2", bulkSize = 300, replications = 10000, intervals = c (95, 99))" and got the results.

Anyway, I will check my input data. 

Thanks again.

**Comment by wangyuu** [comment]
Dear bmansfeld:
       I know the reason. My input SNP table is not filtered well. Multiple alleles like below existed.
"Chr11   19224   C       G,T     10,85,59        154     99      4506,1753,1880,2430,0,2611      2,46,68 116     99      3651,2186,2147,1393,0,1293" 
When I filtered these sites, I can run the command and got the results.
Thanks again.

**Comment by bmansfeld** [comment]
Great! 
This is because QTLseqr parses those columns and saw the "," and didn't understand.
Happy this was resolved.
-Ben

**Comment by cjchen5** [comment]
Hi Ben,
I also got problem in runGprimeAnalysis when I use version 0.7.5.2
Here is my code, same with your guide.
```
> df_filt <- runGprimeAnalysis(
+   SNPset = df_filt,
+   windowSize = 1e6,
+   outlierFilter = "deltaSNP")

```
Here is output:
```
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Error in locfit::locfit(Stat ~ locfit::lp(POS, h = windowSize, deg = 0),  : 
  fewer than one row in the data
In addition: There were 37 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In lfproc(x, y, weights = weights, cens = cens, base = base,  ... :
  Estimated rdf < 1.0; not estimating variance
```
Could you tell me what might cause that error? 
Thanks!

**Comment by bmansfeld** [comment]
it seems that your data aren't properly formatted.
Please open a new issue post a head of your df_filt and we can try and resolve it.
Ben

**Comment by cjchen5** [comment]
Sure! Thank you for your quick response!

**Comment by Zakeel-stack** [comment]
Hi Ben,
When I was running a runGprimeAnalysis, I got the following error and I was wondering how I can resolve this. 
Error in mutate_impl(.data, dots) : 
  Evaluation error: fewer than one row in the data.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Appreciate your advice on this. 
Zakeel

**Comment by bmansfeld** [comment]
Zekeel, 
It seems that your data frame is empty.
Please check the import and filtering steps.
If there is still an issue please open another issue.
Ben

**Comment by Zakeel-stack** [comment]
Hi.

I think the import and filtering steps are okay. For the plant I am working with, the chromosome positions are still unknown and I have used the contig position in place of chromosome number. Is it okay or is it the reason for the error?
How can I overcome this or proceed with the analysis with the contig information only.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
