### ISSUE TITLE
some error comes

### ISSUE THREAD

**Issue by dksam** [bmansfeld/QTLseqR#14]
> #Import SNP data from file
> df <-
+     importFromGATK(
+         file = file,
+         highBulk = HighBulk,
+         lowBulk = LowBulk,
+         chromList = Chroms
+     )
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'SNPs_from_GATK.table': No such file or directory

**Comment by bmansfeld** [comment]
Sorry this is my mistake trying to quickly fix a related bug last night. 
Should be fixed from v 0.7.5.2 .
Please post another issue if you have any.
Thanks for catching this.
Ben
