### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by cshen226** [bmansfeld/QTLseqR#15]
library("QTLseqr")
 library("Yang2013data")
rawData <- system.file("extdata","Yang_et_al_2013.table",package = "Yang2013data",mustWork = TRUE)
HighBulk <- "SRR834931"
LowBulk <- "SRR834927"
Chroms <- paste0(rep("Chr", 12), 1:12)
df <- importFromGATK(file = rawData,highBulk = HighBulk,lowBulk = LowBulk,chromList = Chroms)
###Run here and the error is as follows
Error in setNames(rep(list(readr::col_integer()), length(int_matches)),  : 
  unused argument (int_matches)
###Please help me how should this solve?

**Comment by bmansfeld** [comment]
Sorry I can't reproduce this bug.
Please make sure you are running the latest version of QTLseqr V 0.7.5.2
