### ISSUE TITLE
chromosomes removed without a reason

### ISSUE THREAD

**Issue by realgc** [bmansfeld/QTLseqR#18]
Hi,
I'm using QTLseqr and when it comes to the step
`df <- importFromGATK(file = rawData, highBulk = aBulk, lowBulk = bBulk, chromList = Chroms)`
it shows
`Removing the following chromosomes: 1, 2, 3, 4, 5`
That's all chromosomes I have! Does anyone have any idea why this is happening?

**Comment by bmansfeld** [comment]
Hi,
Whats stored in your `Chroms` variable? 
If it doesn't exactly match the names of the chromosomes in your data frame then `importFromGATK` will remove any line which doesn't contain one of the chromosome names supplied to `chromList`. 
If you don't need to exclude any chromosomes then you can leave `chromList = NULL` which is the default (i.e. you don't need to even write it)
Hope that helps.
Ben

**Comment by realgc** [comment]
Thanks Ben! 
I have solved the issue by deleting the `Chroms <- paste0()`, and your response also works.
Best,

**Comment by bmansfeld** [comment]
Great! 
Good luck with the rest of your research.
