### ISSUE TITLE
Cannot install "tools" for QTLseqr

### ISSUE THREAD

**Issue by DaRinker** [bmansfeld/QTLseqR#19]
Hi.

I'm getting the following error when trying to install QTLseqr:

```
> devtools::install_github("bmansfeld/QTLseqr")
Downloading GitHub repo bmansfeld/QTLseqr@master
Error: Could not find tools necessary to compile a package
```
Any idea what this means?

Thanks for any help

**Comment by bmansfeld** [comment]
You need to install Rtools for windows

**Comment by DaRinker** [comment]
Ah! Thank you so much!

**Comment by bmansfeld** [comment]
Cool! happy to help

**Comment by khushbrar7** [comment]
Hi,
I'm trying to install QTLseqr, but keep getting the following error:

> devtools::install_github("bmansfeld/QTLseqr")
Downloading GitHub repo bmansfeld/QTLseqr@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/bmansfeld/QTLseqr/tarball/master'

**Comment by bmansfeld** [comment]
@khushbrar7 This isn't a problem on my end. Try updating your R and Rstudio or on a different machine. The package is available and install-able from that command. 
Sorry I don't have a better response,
Ben

**Comment by khushbrar7** [comment]
@bmansfeld Thank you for the response.
