### ISSUE TITLE
Attempting to use QTLseqR..learning :)

### ISSUE THREAD

**Issue by ShakerKousik** [bmansfeld/QTLseqR#20]
Hi Ben I just downloaded QTLseqr latest version and tried to run the example.  It kept giving the below message. Thanks for any help.
Shaker

> df<-importFromGATK(file = file, highBulk = HighBulk, lowBulk = LowBulk, chromList = Chroms)
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'SNPs_from_GATK.table': No such file or directory

**Comment by floschill** [comment]
Hi Shaker,
you probably tried executing the following code:
```R
#load the package
library("QTLseqr")

#Set sample and file names
HighBulk <- "SRR834931"
LowBulk <- "SRR834927"
file <- "SNPs_from_GATK.table"

#Choose which chromosomes will be included in the analysis (i.e. exclude smaller contigs)
Chroms <- paste0(rep("Chr", 12), 1:12)

#Import SNP data from file
df <-
    importFromGATK(
        file = file,
        highBulk = HighBulk,
        lowBulk = LowBulk,
        chromList = Chroms
     )
```

This requires a table-file called "SNPs_from_GATK.table" in your working directory, which is not provided by QTLseqr when you just download and install the package. I would recommend reading the vignette ([here](https://github.com/bmansfeld/QTLseqr/raw/master/vignettes/QTLseqr.pdf)), starting with the chapter "Standard workflow", that also describes how to download and use the Yang2013 example data.
Flo

**Comment by bmansfeld** [comment]
closed
