### ISSUE TITLE
difference between Upward peaks and Downward peaks ?

### ISSUE THREAD

**Issue by qindan2008** [bmansfeld/QTLseqR#21]
Hi, 
When run QTLseqr, sometimes value of ∆(SNP-index) was positive, the peak was upward. But sometimes value of ∆(SNP-index) was negative, and the peak was downward. 

So, how to interpret negative ∆(SNP-index) ？What is the biological significance?

Thank you very much.

**Comment by bmansfeld** [comment]
Hi,
Positive delta SNP values indicate a qtl derived from the parent that isn't the reference.
I negative peak represents qtl contributed by the reference parent.
Hope this makes sense,
Ben

**Comment by qindan2008** [comment]
Does the reference parent refer to high bulk sample? The parent that isn't the reference refers to low bulk sample?

Thanks a lot.

**Comment by bmansfeld** [comment]
depends on your set up. 
I usually set the parent with the low bulk phenotype as the reference. 
That way the peaks with high delta SNP represent areas contributing to the alternate parent which has the high-bulk phenotype 
High peaks - high phenotype value makes sense in my head.
Ben
