### ISSUE TITLE
I cann't install QTLseqr. Could you help me?

### ISSUE THREAD

**Issue by ghost** [bmansfeld/QTLseqR#22]
Dear Ben

I got this error message when I installed the QTLseqr.

devtools::install_github("bmansfeld/QTLseqr")
Error: Failed to install 'unknown package' from GitHub:
  invalid multibyte string, element 1

I tried to install QTLseqr in various versions of R; R 3.3, R3.4, R3.5, and R3.6

'Rtools' and 'devtools' were already installed in my computer.

Could you help me?

Sincerely,

HTKim

**Comment by bmansfeld** [comment]
This most likely has something to do with language compatibility issues with your system.
Not sure how to fix it.
Try on another machine

**Comment by ghost** [comment]
> This most likely has something to do with language compatibility issues with your system.
> Not sure how to fix it.
> Try on another machine

Thanks Ben!
QTLseqr was well installed on my linux computer.
This package is really helping me!

**Comment by kmosi0** [comment]
I got this error too,it might occur in Rstudio .    I solve it by using this code: 
Sys.setlocale(category = "LC_ALL", locale = "us")

**Comment by bmansfeld** [comment]
Awesome! thanks for the help to anyone who may need it!
