### ISSUE TITLE
Problem in G G` statistic calculation: Error in locfit::locfit(Stat ~ locfit::lp(POS, h = windowSize, deg = 0),  :    fewer than one row in the data

### ISSUE THREAD

**Issue by anjugiri** [bmansfeld/QTLseqR#26]
Hi Ben, I have a problem calculating G statics using function runGprimeAnalysis. Here is the copy from my console:

> df_filt <- runGprimeAnalysis(df_filt,
+   windowSize = 1e7,
+   outlierFilter = "deltaSNP",
+   filterThreshold = 0.1)
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Error in locfit::locfit(Stat ~ locfit::lp(POS, h = windowSize, deg = 0),  : 
  fewer than one row in the data
In addition: There were 50 or more warnings (use warnings() to see the first 50)

I am trying to run on the wild population, where F1s are open pollinated to get F2s and bulks are aligned to a de novo reference assembly with ~100000 contigs.

I checked to see if the df is missing any col, but its complete. Attached is the tail of the df. 

<img width="996" alt="Screen Shot 2020-01-15 at 7 35 27 AM" src="https://user-images.githubusercontent.com/51096203/72434485-b5d5c180-3769-11ea-80e2-b85911b8bc1d.png">

**Comment by bmansfeld** [comment]
Hi, 
I think the problem is due to the assembly and the window size.
But just to make sure, what happens if you run `runQTLseqAnalysis()` first?
Does it work? after it works can you run Gprime on the new df that comes out of `runQTLseqAnalysis`?

If not try lowering the window size and perhaps try discarding many of the very small contigs. 
Let me know what you find out.. 
I'll try to help as best as possible
Ben

**Comment by anjugiri** [comment]
Hi Ben,

Thank you for your response. 

Lowering the window size doesn't help, I will try by dropping some contigs. 
`QTLseqAnalysis` runs without error, and attached above (df_filt) is the df frame generated after running `QTLseqAnalysis` as follows:

df_filt <- runQTLseqAnalysis(df_filt, windowSize = 1e6,
+                                    popStruc = "F2",
+                                    bulkSize = c(78,103), replications = 10000,
+                                    intervals = c(95, 99) )

The Gprime is on the df `df_filt` that comes out of the runQTLseqAnalysis, but doesn't seem to help.

I will let try more with additional filtering in the contigs and will let you know. 

Thank you,
Anju

**Comment by bmansfeld** [comment]
Hey Anju,
Did you figure this out?
If not and you feel comfortable sharing your .table file I can take a look.
Let me know,
Ben

**Comment by anjugiri** [comment]
[C32_w_parents_allsites.vcf.table.zip](https://github.com/bmansfeld/QTLseqr/files/4091696/C32_w_parents_allsites.vcf.table.zip)

Ben, Thank you very much. Here is the data frame I worked with, I tried with several different files but got into the same error. To start, I just filtered to remove NAs from the file.

**Comment by anjugiri** [comment]
Never mind. The issue get solved after filtering. Thank you very much, the package is very helpful.

**Comment by bmansfeld** [comment]
Thanks for letting me know and for the good feedback!
Would you mind explaining what you think the issue was.
This way if other people have a similar problem they can see what solved it.
Thanks,
Ben

**Comment by anjugiri** [comment]
Some of the contigs were very short (in Kbs) and the window in them had very few SNP, I did filter for windows having at least 5 SNP which helped to solve this issue. Thank you for your suggestion.
