### ISSUE TITLE
importFromTable

### ISSUE THREAD

**Issue by GracielaCaruso** [bmansfeld/QTLseqR#27]
Hello!
I am trying to use the QTLsegr package, but I have trouble with the ImportFromTable function.
I have my data in comma delimited file (csv). The head is:

CHROM | POS | id | REF | ALT | AD_REF.LV | AD_ALT.LV | AD_REF.CV | AD_ALT.CV
Chr01 | 22492233 | 1122 | G | A | 9 | 5 | 8 | 4
Chr01 | 22492228 | 1141 | G | A | 10 | 6 | 11 | 3
Chr01 | 22492206 | 1393 | G | A | 11 | 5 | 9 | 3
Chr01 | 22492264 | 1429 | C | T | 11 | 5 | 10 | 3

When I run the function, I get this message:
"Error in importFromTable(file = "slSHQTLseqr.csv", highBulk = "HighBulk", :
No 'CHROM' coloumn found.
Además: Warning message:
The following named parsers don't match the column names: CHROM, POS "

I will be very grateful if you can help me solve the problem!

Thanks in advance!

Graciela Caruso

**Comment by bmansfeld** [comment]
Graciela thanks for opening the issue.
Before anything else, and just as a check, when you pasted the head of the csv were the `|` added by you manually? If they are in the actually csv then this is the problem.
Let me know,
Ben

**Comment by GracielaCaruso** [comment]
Ben, thanks for your attention.
I copied the first rows of Excel. The symbol was added when I pasted the header here. The csv file has not the symbol ( | ).
Graciela

**Comment by bmansfeld** [comment]
ok good! just checking.. do you mind sending me the top 100 rows of your csv? 
I can check what is breaking the import function.

**Comment by GracielaCaruso** [comment]
Excuse me for my incorrect English!
I send you the file

**Comment by bmansfeld** [comment]
No need to apologize!  My Spanish is _a lot_ worse!!!

**Comment by bmansfeld** [comment]
Hi I never received the file from you.
You could upload a link here or email me.
bmansfeld [at] danforthcenter.org

**Comment by GracielaCaruso** [comment]
Hi Ben
I send you the file again

Thanks you

Graciela


---------- Forwarded message ---------
De: Graciela Caruso <gbcaruso67@gmail.com>
Date: mar., 21 ene. 2020 a las 19:13
Subject: Re: [bmansfeld/QTLseqr] importFromTable (#27)
To: bmansfeld/QTLseqr <
reply@reply.github.com>


Excuse me for my incorrect English!
I send you the file
