### ISSUE TITLE
i meet a bug and need your help.

### ISSUE THREAD

**Issue by liuxiaowei0401** [bmansfeld/QTLseqR#30]
Hi,i m so great sorry to trouble you.when i ues runQTLseqAnalysis to calculate the CI of 99% and 95%,i found when i set the windowSize is 1Mb,the error will arrival 'newsplit :out of vertex space',i thought my computer‘s space to little,but i can not sovle the problem when i use a bigger space computer.so i have to take the qustion to you for help.

**Comment by bmansfeld** [comment]
Hi,
I'm not at my computer right now to write a more detailed response.
But in short please see the vignette for information about this error. 
In short a 1Mb window is probably too small for your genome.
Ben

**Comment by liuxiaowei0401** [comment]
sorry,Maybe I didn't express myself clearly。not only i set the windows is 1Mb， but when the window is less than 10MB，the error is arrival.i handle the maize genome。i have ask sameone of research the maize,they have found the same error either.

Not only set to 1MB,

**Comment by bmansfeld** [comment]
Hi, 
Please keep in mind the window employed in QTLseqr is a tricube-smoothed window (weighted by distance from middle) not a rectangular window (ie equally weighted average). Based on the discussion in Magwene et al., 2011 it should cover as much regions that correspond to 25 cM or even more. Please see that paper for explanations.
So considering a maize genome of +2Gb that should correspond to much higher window sizes. 

If you are still intent on using a window of that size I would point you again to the [vignette ](https://github.com/bmansfeld/QTLseqr/blob/master/vignettes/QTLseqr.pdf) were I mention tweaking the `maxk` parameter in either the `runQTLseqAnalysis` or the `runGprimeAnalysis` functions. I don't have any advice about how much to change this value to. The default is 100.
Please let us know here what worked for you if you go this route. 

Hope that helps a little,
Ben

**Comment by liuxiaowei0401** [comment]
ok,sorry, maybe I'm just a student, I can't understand the specific usage of thispackage. At present, I have calculated the SNP index of parent 1 and a mixed pool through VCF, and listed their sequencing depth. I want to ask if I can use this information to calculate 95% and 99% CI by displacement test?

**Comment by bmansfeld** [comment]
I'm not sure I understand the question? You need two bulks in the approach we use. 

Is this a new question or related to the previous Error message you were getting?

Please fallow along the example data set provided and I hope that will clear up the usage of the package and data types used. I spent a good amount of time trying to make the pipeline as clear and helpful as possible.

 If you have other specific issues or questions please open a new issue and I will do my best to help!

**Comment by xiekunwhy** [comment]
I think the window size is not the main reason to cause newsplit :out of vertex space error, but the marker density is. So if there are large gaps (have no enough markers) in your chromosomes, the error may always happen until your window size is larger than the max gap.

**Comment by bmansfeld** [comment]
Thanks for the comment!
Yes I suppose you can look at it from that perspective as well. For example, I've faced this error or had windows with no/only one marker when using data from gbs experiments. These are a lot less dense as you say and as such require much larger windows.
Using WGS data though should not have the same problem as typically you mean that expect to find a few SNPs per mb in a randomly segregating population with dis similar parents of origin with a 30mb chromosome.  So again sometimes if the genome is very large a much larger window is appropriate and as I mentioned above these can be 20 cM in size or so.
Always there is the option to increase the `maxk` as described above.
Hope the discussion helps.

**Comment by liuxiaowei0401** [comment]
I see what you mean. Thank you very much for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 晚上10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bmansfeld/QTLseqr] i meet a bug and need your help. (#30)





 
I think the window size is not the main reason to cause newsplit :out of vertex space error, but the marker density is. So if there are large gaps (have no enough markers) in your chromosomes, the error may always happen until your window size is larger than the max gap.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
