### ISSUE TITLE
Error: argument 'x' contains missing values

### ISSUE THREAD

**Issue by Deeptirao** [bmansfeld/QTLseqR#35]
Please help me in resolving the error of missing values for x, which is not allowing me to calculate G prime. 

> df_filt <- runGprimeAnalysis(
+     SNPset = df_filt,
+     windowSize = 1e6,
+     outlierFilter = "deltaSNP")
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Using deltaSNP-index to filter outlier regions with a threshold of 0.1
Estimating the mode of a trimmed G prime set using the 'modeest' package...
**Error: argument 'x' contains missing values**

My file looks like this:
> head(df_filt)
  CHROM  POS          REF                        ALT AD_REF.LOW AD_ALT.LOW DP.LOW GQ.LOW PL.LOW SNPindex.LOW AD_REF.HIGH AD_ALT.HIGH DP.HIGH
1  Chr1 1058            T                         TA         28         18     46     NA     NA    0.3913043          41          17      58
2  Chr1 2541            T                         TC         31          4     35     NA     NA    0.1142857          25           2      27
3  Chr1 2559        CTAGG                ATAGT,CTAGT         32         10     42     NA     NA    0.2380952          28           9      37
4  Chr1 2627        GCTTC          ACTCT,ACGTC,GCTCC         41         18     59     NA     NA    0.3050847          NA          NA      40
5  Chr1 2653            C                          T         33         31     64     NA     NA    0.4843750          29          13      42
6  Chr1 2722 ATTTTTTTTGAG ATTTTTTTTTAAG,ATTTTTTTTAAA         NA         NA     57     NA     NA           NA          24          15      39
  GQ.HIGH PL.HIGH SNPindex.HIGH   REF_FRQ     deltaSNP nSNPs tricubeDeltaSNP minDP tricubeDP      CI_95      CI_99
1      NA      NA    0.29310345 0.6634615 -0.098200900   619    -0.009587027    46        30 -0.4333333 -0.5333333
2      NA      NA    0.07407407 0.9032258 -0.040211640   622    -0.009638414    27        30 -0.4333333 -0.5333333
3      NA      NA    0.24324324 0.7594937  0.005148005   622    -0.009639038    37        30 -0.4333333 -0.5333333
4      NA      NA            NA        NA           NA   622    -0.009641394    40        30 -0.4333333 -0.5333333
5      NA      NA    0.30952381 0.5849057 -0.174851190   622    -0.009642295    42        30 -0.4333333 -0.5333333
6      NA      NA    0.38461538        NA           NA   622    -0.009644686    39        30 -0.4333333 -0.5333333

**Comment by bmansfeld** [comment]
Hi sorry for the delayed response.
Seems like you have lots of NA missing values in your dataset. 
Try filtering out INDELS before importing into qtlseqr that may be the problem (though it shouldn't really)
