### ISSUE TITLE
Error: The subscript for category ' closure ' is wrong

### ISSUE THREAD

**Issue by ChengYunazhi** [bmansfeld/QTLseqR#4]
Hi, Ben

when I call function "getSigRegions" to get the QTL snps, error was reported by R, as below:

Error: The subscript for category ' closure ' is wrong

---

I check source code of this function，found this：

![qq 20180326113724](https://user-images.githubusercontent.com/13846735/37885851-100edc3c-30ea-11e8-9ebe-1c8b4dd50f47.png)

'table' is a function in R, is this the source of error?

Thanks！

**Comment by bmansfeld** [comment]
Hey,
Thanks for the feedback.
I renamed the variable in all the export functions.
I should not be using conserved function names.

Let me know if it fixes the error or something else is causing it. 
Those functions run for me. 
I'll leave the issue open until you tell me it works for your data.
Thanks.
Ben

**Comment by ChengYunazhi** [comment]
Thanks, Ben.

I found the reason is  dplyr packages running on my machine needs to update, when updating the packages to latest version, thoses functions work well, and output what we want.

**Comment by bmansfeld** [comment]
Great. Thanks for letting me know. I updated the functions to not use `table` in any case.
Good luck with your research!
-Ben
