### ISSUE TITLE
getQTLTable without running runGprimeAnalysis

### ISSUE THREAD

**Issue by liufy11** [bmansfeld/QTLseqR#41]
Hello,
    To my knowledge , runGprimeAnalysis and runQTLseqAnalysis are two seperate function. after running runQTLseqAnalysis, I want  to get QTL region using getQTLTable, but the screen says "Error in getQTLTable(SNPset = df_filt, alpha = 0.01, interval = 99.9999999,  : Please first use runGprimeAnalysis to calculate q-values".

Can't I only use runQTLseqAnalysis and get the QTL region ?

If I run runGprimeAnalysis  and then run runQTLseqAnalysis , which is the result comes from ? runGprimeAnalysis or runQTLseqAnalysis

**Comment by bmansfeld** [comment]
Hi,
the default `method` parameter for `getQTLTable()` is `method = "Gprime"`. So when you didn't include that argument when you ran the code it defaults to that.  Set `method = "QTLseq"` to get those results.
Good luck!
Ben
