### ISSUE TITLE
Installation failed: error in running command  when use devtools::install_github("bmansfeld/QTLseqr") to Install

### ISSUE THREAD

**Issue by haohui123** [bmansfeld/QTLseqR#42]

**Comment by bmansfeld** [comment]
Sorry i can't help with out more information. 
I would recommend installing the latest version of R and Rstudio.
Ben

**Comment by haohui123** [comment]
ThanK you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bmansfeld/QTLseqr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 凌晨4:55
收件人:&nbsp;"bmansfeld/QTLseqr"<QTLseqr@noreply.github.com&gt;;
抄送:&nbsp;"杨好慧"<475889337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bmansfeld/QTLseqr] Installation failed: error in running command  when use devtools::install_github("bmansfeld/QTLseqr") to Install (#42)





 
Closed #42.

**Comment by haohui123** [comment]
library("QTLseqr")
&gt; #指定文件的目录
&gt; setwd("/data/pub/yanghh/R")
&gt; #Set sample and file names
&gt; #Set sample and file names
&gt; HighBulk <- "QT4Rpool"
&gt; LowBulk <- "QT4Spool"
&gt; file <- "demo.20QT4reformnoscaffold.table"
&gt; #Choose which chromosomes will be included in the analysis (i.e. exclude smaller contigs)
&gt; Chroms <- paste0(rep("R0", 9), 1:9)
&gt; #Import SNP data from file
&gt; df <-
+ importFromGATK(
+ file = file,
+ highBulk = HighBulk,
+ lowBulk = LowBulk,
+ chromList = Chroms
+ )
erSNPs(
SNPset = df,
refAlleleFreq = 0.20,
minTotalDepth = 100,
maxTotalDepth = 400,
minSampleDepth = 40,
minGQ = 99
|==================================================================| 100% 166 MB
Removing the following chromosomes:&nbsp;
&gt; #Filter SNPs based on some criteria
&gt; df_filt <-
+ filterSNPs(
+ SNPset = df,
+ refAlleleFreq = 0.20,
+ minTotalDepth = 100,
+ maxTotalDepth = 400,
+ minSampleDepth = 40,
+ minGQ = 99
+ )
Filtering by reference allele frequency: 0.2 <= REF_FRQ <= 0.8
...Filtered 219647 SNPs
Filtering by total sample read depth: Total DP &gt;= 100
...Filtered 2283058 SNPs
Filtering by total sample read depth: Total DP <= 400
...Filtered 4 SNPs
Filtering by per sample read depth: DP &gt;= 40
...Filtered 7647 SNPs
Filtering by Genotype Quality: GQ &gt;= 99
...Filtered 2102 SNPs
Original SNP number: 2614834, Filtered: 2512458, Remaining: 102376
&gt; #Run G' analysis
&gt; df_filt <- runGprimeAnalysis(SNPset = df_filt,
+ windowSize = 1e6,
+ outlierFilter = "deltaSNP")
Counting SNPs in each window...
,
intervals = c(95, 99)
)Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Using deltaSNP-index to filter outlier regions with a threshold of 0.1
Estimating the mode of a trimmed G prime set using the 'modeest' package...
Calculating p-values...
&gt; #Run QTLseq analysis
&gt; df_filt <- runQTLseqAnalysis(
+ SNPset = df_filt,
+ windowSize = 1e6,
+ popStruc = "F2",
+ bulkSize = c(30, 30),
+ replications = 10000,
+ intervals = c(95, 99)
+ )
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Returning the following two sided confidence intervals: 95, 99
Variable 'depth' not defined, using min and max depth from data: 40-194
Assuming bulks selected from F2 population, with 30 and 30 individuals per bulk.
Simulating 10000 SNPs with reads at each depth: 40-194
Keeping SNPs with &gt;= 0.3 SNP-index in both simulated bulks
Joining, by = "tricubeDP"
&gt; #Plot
&gt; plotQTLStats(
+ SNPset = df_filt,
+ var = "Gprime",
+ plotThreshold = TRUE,
+ q = 0.01
+ )
A_QTL.csv"
)
&gt; plotQTLStats(
+ SNPset = df_filt,
+ var = "deltaSNP",
+ plotIntervals = TRUE)
&gt; #export summary CSV
&gt; getQTLTable(
+ SNPset = df_filt,
+ alpha = 0.01,
+ export = TRUE,
+ fileName = "my_BSA_QTL.csv"
+ )
&nbsp; CHROM qtl&nbsp; &nbsp; start&nbsp; &nbsp; &nbsp; end&nbsp; &nbsp;length nSNPs avgSNPs_Mb peakDeltaSNP
1&nbsp; &nbsp;R05&nbsp; &nbsp;1&nbsp; &nbsp;359111&nbsp; 2707785&nbsp; 2348674&nbsp; 1348&nbsp; &nbsp; &nbsp; &nbsp; 574&nbsp; &nbsp; 0.3715301
2&nbsp; &nbsp;R08&nbsp; &nbsp;2&nbsp; &nbsp;481924&nbsp; 1690113&nbsp; 1208189&nbsp; &nbsp;166&nbsp; &nbsp; &nbsp; &nbsp; 137&nbsp; &nbsp; 0.4497638
3&nbsp; &nbsp;R08&nbsp; &nbsp;3&nbsp; 2315373&nbsp; 3233279&nbsp; &nbsp;917906&nbsp; &nbsp; 70&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;76&nbsp; &nbsp; 0.5995933
4&nbsp; &nbsp;R08&nbsp; &nbsp;4&nbsp; 5575282 21288165 15712883&nbsp; 2731&nbsp; &nbsp; &nbsp; &nbsp; 174&nbsp; &nbsp; 0.6366040
5&nbsp; &nbsp;R08&nbsp; &nbsp;5 27365953 27493493&nbsp; &nbsp;127540&nbsp; &nbsp; &nbsp;2&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;16&nbsp; &nbsp; 0.3348856
&nbsp; posPeakDeltaSNP avgDeltaSNP maxGprime posMaxGprime meanGprime&nbsp; sdGprime
1&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1892524&nbsp; &nbsp;0.3644229&nbsp; 17.80104&nbsp; &nbsp; &nbsp; 1892524&nbsp; &nbsp;16.73321 0.7904796
2&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;1317676&nbsp; &nbsp;0.4175901&nbsp; 19.03438&nbsp; &nbsp; &nbsp; 1280127&nbsp; &nbsp;18.07673 1.0102488
3&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2997114&nbsp; &nbsp;0.5769150&nbsp; 18.61783&nbsp; &nbsp; &nbsp; 2622530&nbsp; &nbsp;17.06866 0.7511737
4&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;6880353&nbsp; &nbsp;0.4678844&nbsp; 32.52107&nbsp; &nbsp; &nbsp; 6885361&nbsp; &nbsp;22.88308 3.2228024
5&nbsp; &nbsp; &nbsp; &nbsp; 27493493&nbsp; &nbsp;0.3001423&nbsp; 19.11753&nbsp; &nbsp; &nbsp;27493493&nbsp; &nbsp;17.21068 2.6966858
&nbsp; &nbsp; &nbsp; &nbsp; AUCaT&nbsp; &nbsp; &nbsp;meanPval&nbsp; &nbsp; meanQval
1&nbsp; &nbsp;3430379.4 2.550512e-04 0.007391167
2&nbsp; &nbsp;3010778.9 1.655678e-04 0.005890071
3&nbsp; &nbsp;1997053.7 2.254567e-04 0.006930349
4 132628359.7 5.871937e-05 0.003031114
5&nbsp; &nbsp; 253383.5 2.591057e-04 0.007304724
&gt;&nbsp;
