### ISSUE TITLE
#REEOR# importFromGATK# Error in file(file, "rt") : cannot open the connection

### ISSUE THREAD

**Issue by haohui123** [bmansfeld/QTLseqR#43]
df <-
+ importFromGATK(
+ file = file,
+ highBulk = HighBulk,
+ lowBulk = LowBulk,
+ chromList = Chroms
+ )
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'Yang_et_al_2013.table': No such file or directory

)> #Set sample and file names
> HighBulk <- "SRR834931"
> LowBulk <- "SRR834927"
> file <- "SNPs_from_GATK.table"
> #Choose which chromosomes will be included in the analysis (i.e. exclude smaller contigs)
> Chroms <- paste0(rep("Chr", 12), 1:12)
> #Import SNP data from file
> df <-
+ importFromGATK(
+ file = file,
+ highBulk = HighBulk,
+ lowBulk = LowBulk,
+ chromList = Chroms
+ )
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'SNPs_from_GATK.table': No such file or directory

**Comment by bmansfeld** [comment]
Hello,
Please read the more detailed instructions in the vignette.
https://github.com/bmansfeld/QTLseqr/raw/master/vignettes/QTLseqr.pdf
This will explain  where to download these trial data.
Ben
