### ISSUE TITLE
The script running normal and no error produced, why no plot generated? just only produce a table of CSV

### ISSUE THREAD

**Issue by haohui123** [bmansfeld/QTLseqR#44]
Help my QTLseqr was installed in linux R envs, R was installed use anconda, the QTLseqr installed success, but when running my script, though no error produced, but the Rplots.pdf and df had nothing!
Has anyone meet this situation? 

> plotQTLStats(
+ SNPset = df_filt,
+ var = "Gprime",
+ plotThreshold = TRUE,
+ q = 0.01
+ )
> plotQTLStats(
+ SNPset = df_filt,
+ var = "deltaSNP",
+ plotIntervals = TRUE)
> getQTLTable(
+ SNPset = df_filt,
+ alpha = 0.01,
+ export = TRUE,
+ fileName = "my_BSA_QTL1.csv"
+ )
  CHROM qtl    start      end   length nSNPs avgSNPs_Mb peakDeltaSNP
1   R05   1     2404  2923609  2921205  1689        578    0.3715301
2   R08   2   356332  3308448  2952116   316        107    0.5995971
3   R08   3  5518535 21451977 15933442  2755        173    0.6366040
4   R08   4 27354643 27493493   138850     4         29    0.3348856
  posPeakDeltaSNP avgDeltaSNP maxGprime posMaxGprime meanGprime sdGprime
1         1892524   0.3606035  17.80104      1892524   16.34035 1.059533
2         3027509   0.4555751  19.03438      1280127   17.04648 1.551114
3         6880353   0.4669769  32.52107      6885361   22.81858 3.327091
4        27493493   0.2800255  19.11753     27493493   16.10660 2.012530
      AUCaT     meanPval    meanQval
1   5917302 0.0002306070 0.006173703
2   7621865 0.0001949842 0.005554059
3 147785964 0.0000461582 0.002235581
4    381450 0.0002735495 0.006789872
>

**Comment by bmansfeld** [comment]
try something like this to save your plot
```
# Print the plot to a pdf file
pdf("myplot.pdf")
myplot <- plotQTLStats(paramaters.....)
print(myplot)
dev.off()
```
