### ISSUE TITLE
Error: Problem with `mutate()` column `tricubeDeltaSNP`

### ISSUE THREAD

**Issue by xiaoaozqd** [bmansfeld/QTLseqR#47]
# prepare the file
gatk VariantsToTable -R ${RefDir}/$Ref -V merge.SNP.filter.vcf \
-F CHROM -F POS -F REF -F ALT \
-GF AD -GF DP -GF GQ -GF PL \
-O merge.snp.table

HighBulk="R"
LowBulk="S"
rawData="merge.snp.table"
Chroms <- "Chr1"

# read file
`
df <-
importFromGATK(
file =rawData,
highBulk =HighBulk,
lowBulk =LowBulk,
chromList =Chroms
)
`
#output
`
head(df)  

  CHROM    POS REF ALT AD_REF.LOW AD_ALT.LOW DP.LOW GQ.LOW   PL.LOW SNPindex.LOW AD_REF.HIGH AD_ALT.HIGH DP.HIGH GQ.HIGH PL.HIGH SNPindex.HIGH REF_FRQ deltaSNP
1  Chr1 144949   G   C          0          5      5     15 225,15,0            1           0           0       0      NA   0,0,0           NaN       0      NaN
2  Chr1 144955   G   A          0          5      5     15 225,15,0            1           0           0       0      NA   0,0,0           NaN       0      NaN
3  Chr1 144979   T   C          0          6      6     18 270,18,0            1           0           0       0      NA   0,0,0           NaN       0      NaN
4  Chr1 144984   C   A          0          6      6     18 270,18,0            1           0           0       0      NA   0,0,0           NaN       0      NaN
5  Chr1 144986   T   C          0          6      6     18 270,18,0            1           0           0       0      NA   0,0,0           NaN       0      NaN
6  Chr1 519510   A   T          0          0      0     NA    0,0,0          NaN           0           1       1       3  45,3,0             1       0      NaN
`

# filter SNP
`
df_filt <-
filterSNPs(
SNPset =df,
refAlleleFreq =0.20,
minTotalDepth =100,
maxTotalDepth =400,
depthDifference =100,
minSampleDepth =40,
minGQ =99,
verbose =TRUE
)
`
#output

Filtering by reference allele frequency: 0.2 <= REF_FRQ <= 0.8
...Filtered 27647 SNPs
Filtering by total sample read depth: Total DP >= 100
...Filtered 11087 SNPs
Filtering by total sample read depth: Total DP <= 400
...Filtered 447 SNPs
Filtering by per sample read depth: DP >= 40
...Filtered 156 SNPs
Filtering by Genotype Quality: GQ >= 99
...Filtered 486 SNPs
Filtering by difference between bulks <= 100
...Filtered 119 SNPs
Original SNP number: 41064, Filtered: 39942, Remaining: 1122

# Run G' analysis
`
df_filt <- runGprimeAnalysis(
    SNPset = df_filt,
    windowSize = 1e6,
    outlierFilter = "deltaSNP")
`
#output

Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
**Error**: Problem with `mutate()` column `tricubeDeltaSNP`.
i `tricubeDeltaSNP = tricubeStat(POS = POS, Stat = deltaSNP, windowSize, ...)`.
x newsplit: out of vertex space
i The error occurred in group 1: CHROM = Chr1.
Run `rlang::last_error()` to see where the error occurred.
addation: There were 50 or more warnings (use warnings() to see the first 50)

#  version
`                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.5                         
year           2021                        
month          03                          
day            31                          
svn rev        80133                       
language       R                           
version.string R version 4.0.5 (2021-03-31)
nickname       Shake and Throw     `

**Comment by bmansfeld** [comment]
hi, this is explained in the vignette.
Please see Issue #9
