### ISSUE TITLE
argument 'x' contains missing values 

### ISSUE THREAD

**Issue by Nikhilasai1223** [bmansfeld/QTLseqR#48]
> df_filt <- runGprimeAnalysis(df_filt,
+                              windowSize = 1e6,
+                              outlierFilter = "deltaSNP",
+                              filterThreshold = 0.1)
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Calculating G and G' statistics...
Using deltaSNP-index to filter outlier regions with a threshold of 0.1
Estimating the mode of a trimmed G prime set using the 'modeest' package...
Error: argument 'x' contains missing values
I encountered the above error. Please help.

**Comment by bmansfeld** [comment]
Sorry I missed this issue. 
If you are still having problems let me know and we can try to work it out.
I will need more information than what you supplied to try to figure it out.
Ben
