### ISSUE TITLE
windowSize change, popStruc change 

### ISSUE THREAD

**Issue by Gaia416** [bmansfeld/QTLseqR#49]
Hello Ben,
    I have 2 questions in runing the under lines of  QTLseq analysis. 

#Run QTLseq analysis
df_filt <- runQTLseqAnalysis(
  SNPset = df_filt,
  windowSize = 1e6,
  popStruc = "F2",#根据群体结构调整F2或者RIL
  bulkSize = c(160, 160),#根据池中的样本单株数量
  replications = 10000,
  intervals = c(95, 99)
)

The 1st is that how can I change the  "windowSize = 1e6"  to 1e5. 
The 2nd is that how can I change the popStruc = "F2" to "BC1".

looking for your help. 
Thanks. 
Rui

**Comment by bmansfeld** [comment]
Hi Rui,
Thanks for your interest in QTLseqr.
The parameters are adjustable as in any function in R, just set `windowSize = 1e5` etc.
However, I strongly advise to read the section of Magwene et al about window sizes - they should be in the realm of 20 cM and depending on your organism 100kb is typically considered small.
Finally, I'm sorry to say that QTLseqr only supports F2 and RIL populations for these types of analyses as it takes in to account the expected allele frequencies for these pops.
BC1 pops could be hypothetically but I have not coded these options in to the package.
Hope this helps,
Ben

**Comment by Gaia416** [comment]
Hi Ben,
Thanks for your so fast reply.&nbsp;
I got your answer. But I truely want to do BSA with BC1 pops, could you give me some recommend?&nbsp;e.g. some referance papers? or could you help&nbsp;coding these options in to the package? Or&nbsp;if there are some other packages or softwares can do this ...


I'm very sorry to make such a request.&nbsp;But I'm really looking forward to your help.&nbsp;



thanks



Rui



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bmansfeld/QTLseqr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bmansfeld/QTLseqr] windowSize change, popStruc change  (#49)





 
Hi Rui,
 Thanks for your interest in QTLseqr.
 The parameters are adjustable as in any function in R, just set windowSize = 1e5 etc.
 However, I strongly advise to read the section of Magwene et al about window sizes - they should be in the realm of 20 cM and depending on your organism 100kb is typically considered small.
 Finally, I'm sorry to say that QTLseqr only supports F2 and RIL populations for these types of analyses as it takes in to account the expected allele frequencies for these pops.
 BC1 pops could be hypothetically but I have not coded these options in to the package.
 Hope this helps,
 Ben
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bmansfeld** [comment]
Rui, 
You could conceivably run the QTLseq pipeline on a BC1 population with the F2 setting - just keep in mind that the way the confidence intervals are simulated assumes an F2 population. If you have a strong phenotype that you're selecting for then it should work and you will hypothetically still get a peak of deltaSNPindex  ~0.5 for your locus. 
Sorry but I am not planning on adding that functionality in the near future as I just dont have time. 
Let me know if it works out.
Ben
