### ISSUE TITLE
Help me please...

### ISSUE THREAD

**Issue by BTBIIT** [bmansfeld/QTLseqR#50]
Hello bmansfeld.
I keep getting the same error message while installing your package.
It was difficult to solve even with my Google search, and I would like to help you.
First, let's talk about my environment, my OS is Windows 10, and the installation program uses RStudio.
When I run the command devtools::install_github("bmansfeld/QTLseqr") , I get "Error: Failed to install 'unknown package' from GitHub:
  Line starting 'LinkingTo ...' is malformed!"
Maybe it's a reference to LinkingTo in the last line, I think.
On the Internet, using remotes::install_github or using bioconductor, various methods were suggested, but the package could not be installed by either method, and the above message was displayed repeatedly. Here is the code I used to install your package attached and sent. If you have a solution, please let me know.

Thank you in advance.

# QTLseqr v0.7.5.2

## Installation
install.packages("devtools") 
library(devtools)
#### use devtools to install QTL_seqr
devtools::install_github("bmansfeld/QTLseqr")
####  Error : Failed to install 'unknown package' from Github : 
install.packages("remotes")
library(remotes)
remotes::install_github("bmansfeld/QTLseqr")
install_github("bmansfeld/QTLseqr")
####   Line starting 'LinkingTo ...' is malformed!
BiocManager::install("QTLseqr")
#### why install BiocManager... but Error in library("QTLseqr")...

**Comment by plhm** [comment]
Hi all,

I wanted to second @BTBIIT 's issue. I'm having the same trouble while trying to install the package. I've tried it in both R/3.6 and R/4.0.3 in a Linux system.

I have also looked around for issues related to this problem, but could not find a definite answer.

Thanks much!

P

**Comment by bmansfeld** [comment]
Hey folks I just tried a fresh install of R 4.1.3 and Rstudio - I'm running windows 10 btw
I was unaware of any errors in installation up until now and I think that @BTBIIT missed some of the actual error message in their original post. 
So the error I received was:
```
> devtools::install_github("bmansfeld/QTLseqr")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2022-04-11 17:03:53 UTC
```

Doing a quick google search found this issue in devtools https://github.com/r-lib/devtools/issues/1566
Not sure why this error from 2018 is still coming back but following the instructions posted there

```
Sys.unsetenv("GITHUB_PAT")
```
and then installing QTLseqr as usual worked as expected:
```
>devtools::install_github("bmansfeld/QTLseqr")
Downloading GitHub repo bmansfeld/QTLseqr@HEAD
Installing 34 packages: tidyselect, generics, bit, progress, tzdb, hms, bit64, colorspace, viridisLite, RColorBrewer, munsell, labeling, farver, clue, rmutil, stabledist, gss, timeSeries, timeDate, dplyr, vroom, scales, isoband, gtable, statip, stable, fBasics, Rcpp, locfit, tidyr, readr, gtools, ggplot2, modeest
Installing packages into ‘C:/Users/bmans/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/tidyselect_1.1.2.zip'
Content type 'application/zip' length 206653 bytes (201 KB)
downloaded 201 KB
...
...
installing to C:/Users/bmans/Documents/R/win-library/4.1/00LOCK-QTLseqr/00new/QTLseqr/libs/x64
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'QTLseqr'
    finding HTML links ... done
    FilterSNPs                              html  
    ImportFromGATK                          html  
    countSNPs_cpp                           html  
    getFDRThreshold                         html  
    getG                                    html  
    getPvals                                html  
    getQTLTable                             html  
    getSigRegions                           html  
    importFromTable                         html  
    plotGprimeDist                          html  
    plotQTLStats                            html  
    plotSimulatedThresholds                 html  
    runGprimeAnalysis                       html  
    runQTLseqAnalysis                       html  
    simulateAlleleFreq                      html  
    simulateConfInt                         html  
    simulateSNPindex                        html  
    tricubeStat                             html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (QTLseqr)
```

Just make sure you have the relevant RTools installed for your system.

Again doesn't look like it's an error in my package but im not sure maybe stuff has changed in devtools::install since I last worked on QTLseqr? 

In any case let me know if this helps resolve and install for you.
Ben

**Comment by plhm** [comment]
Hi Ben,

Thanks for replying so quickly.

So, the error message that I got is not the same you did. Here's how it looks like:

```
> devtools::install_github("bmansfeld/QTLseqr")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'LinkingTo ...' is malformed!
```

That's all.

I even tried doing what you suggested above, but as expected, that did not work, given that we were not dealing with the same problem.

Curiously, I did try installing QTLseqr in my PC (Windows OS), and it worked like a charm. Therefore, at least for me, the issue appears to be that of installing it in a Linux-based system. The cluster I work at uses a CentOS Linux distribution. Unfortunately, though, my PC is old and could take in memory the dataset I want to run QTLseqr on.

Any chance you could try to reproduce the error in a Linux distribution to see if we get the same error?

Thanks.

P

**Comment by bmansfeld** [comment]
Yeah i can give it a shot on our cluster later this week.
After some skimming stackoverflow et al., similar though not exactly same errors happen to some people for other github based packages. 
Some people report installing R, devtools and other packages through bioconda and that might help?
In the mean time the analysis shouldn't be to taxing or long. Perhaps there is another windows or mac machine you can borrow to run the initial analyses and then transfer the data frames to your linux machine for further exploration.

Sorry I don't have the best answer just right now.

I'll add it to my todo list

**Comment by BTBIIT** [comment]
Hi All,
Thank you all for your interest in my problem.
Although the above solution did not solve it.
And I am getting the same error message as mentioned by plhm above.
As mentioned, my OS is windows 10, and the program I use is RStudio.
Since my time zone is not the same as yours, I apologize for the late check, and once again thank you for your interest in my problem.

Have a nice day everyone.

**Comment by bmansfeld** [comment]
Hi @plhm seems like someone has made a bioconda repo of QTLseqr 0.7.5.2
I haven't tried this yet (we have some issues with conda on our cluster) but worth a shot to install on linux 
https://anaconda.org/bioconda/r-qtlseqr
let me know if it works for you! 
Ben

**Comment by plhm** [comment]
Hey Ben,

Thanks for the heads up. I much appreciate it.

Folks in the cluster at the University I'm at were able to install it for
me. Issues appeared to be due to a version conflict between R packages
installed at the root and packages at my local R installation. I'll try to
look more into this if I have time, but in short: I still don't know what
the issue was, but it got sorted by folks with sudo powers. Perhaps folks
that use the program in their own machines won't have the same issue.

Thanks much, Ben! Works like a charm after I got it running.

P

**Comment by bmansfeld** [comment]
Cool thanks for letting me know.
Hope you got some good results!
