### ISSUE TITLE
cant install this R package

### ISSUE THREAD

**Issue by RADIOMUMM** [bmansfeld/QTLseqR#54]
Hi!
i used the install code on Rstudio ,but  connection is timeout, same for conda.
how can i fix this?

best
jennies

**Comment by bmansfeld** [comment]
Hi,
I actually just tested a new fresh install on a new windows machine. 
I can install qtlseqr on R4.2.2 on windows I made sure to install a new version of Tools to match the new R version.
Try installing a new version of Rtools to match the R version.
Let me know if that works,
Ben

**Comment by RADIOMUMM** [comment]
Hi,Ben
I've fixed this issue！
By using the locally installed method
` devtools::install_local("qtlseqr.zip")`

best
Jennies
