### ISSUE TITLE
Help interpreting odd G'value plot

### ISSUE THREAD

**Issue by badplantgeek** [bmansfeld/QTLseqR#59]
Dr Mansfeld

Thank you for creating this package, it has been very useful in my research.

I am running a QTL-seq analysis with a F2 population and am having a hard time understanding what might be going on with the G'values in one of the scaffolds. See scaffold "5_RagTag" in the image below. Image produced with _plotQTLStats(SNPset = df_filt, var = "Gprime", plotThreshold = TRUE, q = 0.1)_:

![odd_gvalues](https://user-images.githubusercontent.com/116438325/236867979-ea441649-e1c9-4f38-925f-fb958141ff31.JPG)

I don't see similar behavior with the deltaSNP function: plotQTLStats(SNPset = df_filt2, var = "deltaSNP", plotIntervals = TRUE)

![deltasnp](https://user-images.githubusercontent.com/116438325/236868577-47b3e322-4b50-4c0f-b148-3406043ba21c.JPG)

Do you have any thought what might be causing the high values in the G'value approach? Any insights would be much appreciated.

**Comment by bmansfeld** [comment]
Hi,
Happy to hear that QTLseqr is useful for you! 
I understand why you are curious about this result - while Gprime and deltaSNP both rely on the same data sometimes there can be discrepancies between them that don't really make sense. 
The good news is that it seems that you have probably have a qtl on chr5?

See my response here to hopefully gain some insight 
https://github.com/bmansfeld/QTLseqr/issues/53#issuecomment-1191651097

Let me know if you have anymore questions.
Ben
