### ISSUE TITLE
Out of vertex space: Problem adjusting maxk value in locfit.raw

### ISSUE THREAD

**Issue by Somatogenomics** [bmansfeld/QTLseqR#60]
@bmansfeld Thank you so much for your help with my previous question.

I have gotten some results, but since I used the default window size (1 Mb), I may have lost some potential genes of interest to my traits. Therefore, I went ahead and reduced the window size to 100 kb, 500 kb and 50 kb, but I got errors with all of them. 

# Error "newsplit: out of vertex space"

I tried to implement the solution prescribed by increasing the default value of maxk in locfit.raw function but got some errors in return. Below is my code to pass the new maxk value through the locfit.raw

runQTLseqAnalysis <- function(SNPset, windowSize, popStruc, bulkSize, replications, intervals, maxk = 250, ...) {
# write the function copletely from "..."
  fit <- locfit.raw(x, y, maxk = maxk, ...)
  
  # Continue with your function code...
}

What am I doing wrong here?

Thank you in anticipation

**Comment by bmansfeld** [comment]
Your window sizes are too small.
This error is directly attributed to using small window sizes. 
Unfortunately if you tried a 1mb window and you got no signal then you might need to go back to your mapping population and select new bulks.
This is explained in the vignette too.
