### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by gnxsf** [bmansfeld/QTLseqR#65]
It appears there is no license associated with this R package. Is this package open source? If so, could an appropriate license be added? Thank you in advance.

**Comment by bmansfeld** [comment]
Hi,
As defined in the package description this package is under GPL-3
https://github.com/bmansfeld/QTLseqr/blob/5e761379a805b65038c415c8d3ce7aa61abe89dc/DESCRIPTION#L13

Thanks,
Ben
