### ISSUE TITLE
how to define Chroms

### ISSUE THREAD

**Issue by walleyResearch** [bmansfeld/QTLseqR#66]
Hi Ben, 

We made an annotated ref genome composed of thousands of contigs.  The ref genome will be updated with HI-C and anchored to a linkage map once completed.  In the meantime, I have up to 49K contigs some massive, some much smaller.
We have carried out association analyses, and now sequenced the bulks from an F2 pop.

To define the chromList is it possible to define Chroms as 'use all'?
Our aim is to filter the contigs once we have G-prime and QTL data.

Best wishes, Pete

**Comment by bmansfeld** [comment]
Hey Pete,
You can keep chromList empty (default setting for that param is `chromList = NULL`) and then QTLseqr will import everything with out filtering. 
I will caution that plotting 49k contigs will be really challenging for R (and to actually be able to see and read) so you might want to manually filter based on contig size after or before import. 

Good luck 
Ben

**Comment by walleyResearch** [comment]
Thanks Ben.  I have tried that. BUT will definitely filter on contig size!
Best wishes
Pete
