### ISSUE TITLE
Analysis of inbread strains: Help needed

### ISSUE THREAD

**Issue by okendojo** [bmansfeld/QTLseqR#67]
I have four F0 (grandparents) fish strains A, B, C and D. A was crossed with B (AxB) and C was crossed with D (CxD) to give F1. The F1 (AB) and (CD) were then crossed  AB x CD to give F2 generation (ABCD). We have DNA sequence (WGS) from F0 and bulk RNAseq from F2. Can I use this tool to identify eQTLs that define specific genetic traits in F0 using RNAseq data from F2? Could you advise on how to go about this because I am tempted to use this great library.

**Comment by bmansfeld** [comment]
Hi,
Let's separate a few things. I think the population structure would work. The f2 should segregate nicely depending on how the original parents are dis-similar from each other.

In regards to using RNAseq data: There are examples were bulk rnaseq can be used with BSA. Take a look around in the literature there are examples.  in theory if you follow the right Variant Calling pipeline for RNA then it should work. There are other things that you might need to consider when using RNA vs DNA for example allele specific expression could skew allele frequencies. I would make sure to pool equimolar RNA samples from each fish in the bulk! 

Finally, mapping eQTL from the bulk data could work. Make sure the tissue you are sampling is expressing the genes you are interested in. You would need expression data from each individual in the population then pool the high expressing and low expressing if you want to actually map the eQTL though. Lots of work.

Overall, I don't know how big your genome is, but I would rather do dual extractions for DNA and RNA. You will get better genomic resolution with the DNA 

Good luck

**Comment by okendojo** [comment]
I see a clear separation of the parental based on SNPs and unique kmers. My only worry is how to use this library to compare the four groups at once since only two groups can be compared at a time. It's hard to know which are the high and low expressers. I will dig through the literature and see
