### ISSUE TITLE
Error while running runQTLseqAnalysis

### ISSUE THREAD

**Issue by Sameerpython** [bmansfeld/QTLseqR#70]
Hi,

I using QTLSeqr for BSA analysis for the wheat genome. I have the vcf file generated using Freebayes. also have the column names as required by the program.  While executing the runQTLseqAnalysis, I get the following error:
`Error in dplyr::mutate(., tricubeDeltaSNP = tricubeStat(POS = POS, Stat = deltaSNP,  : 
  
ℹ In group 1: `CHROM = 1A`.
Caused by error in `lfproc()`:`

Can I know how to solve this error? 
Thank you!

**Comment by bmansfeld** [comment]
I don't think you are posting the whole error here. 
But if I am guessing correctly it is related to the vertex space

See here: https://github.com/bmansfeld/QTLseqr/issues/60#issuecomment-1550371353

and elsewhere this issue is described.
Please read the vignette too.
Ben
