### ISSUE TITLE
Run runQTLseqAnalysis subscript out of bounds

### ISSUE THREAD

**Issue by trenk-nicolas** [bmansfeld/QTLseqR#72]
I am following the Yang2013data tutorial and when running
`df_filt <- runQTLseqAnalysis(df_filt,
windowSize = 1e6,
popStruc = "F2",
bulkSize = c(385, 430),
replications = 10000,
intervals = c(95, 99)
)`

I get the warning:
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Returning the following two sided confidence intervals: 95, 99
Variable 'depth' not defined, using min and max depth from data: 40-197
Assuming bulks selected from F2 population, with 385 and 430 individuals per bulk.
Simulating 10000 SNPs with reads at each depth: 40-197
Keeping SNPs with >= 0.3 SNP-index in both simulated bulks
Joining with `by = join_by(tricubeDP, CI_95, CI_99)`
Warning message:
There were 5398 warnings in `dplyr::mutate()`.
The first warning was:
ℹ In argument: `nSNPs = countSNPs_cpp(POS = POS, windowSize = windowSize)`.
ℹ In group 1: `CHROM = Chr1`.
Caused by warning in `countSNPs_cpp()`:
! subscript out of bounds (index 67784 >= vector size 67784)
ℹ Run dplyr::last_dplyr_warnings() to see the 5397 remaining warnings. 

---
Backtrace:
    ▆
 1. ├─QTLseqr::runQTLseqAnalysis(...)
 2. │ └─SNPset %>% dplyr::group_by(CHROM) %>% ...
 3. ├─dplyr::mutate(., nSNPs = countSNPs_cpp(POS = POS, windowSize = windowSize))
 4. └─dplyr:::mutate.data.frame(...)

... with 5393 more warnings.
ℹ Run dplyr::last_dplyr_warnings(n = 10) to show more.

Is this anything that could cause problems?

**Comment by bmansfeld** [comment]
Hi I'm not sure what could be causing that. 
Do you have a fresh installation of R and Rstudio? Rtools?

**Comment by bmansfeld** [comment]
I just ran a test on linux on my HPC with a new QTLseqr install. 
I get the same warnings. It looks like everything actually works fine.
I'm not sure what that is from something to do with Rcpp.

Looks like its ok but let me know if you run in to down stream errors.
