### ISSUE TITLE
Problem with a dependency

### ISSUE THREAD

**Issue by mpaulsmeyer** [bmansfeld/QTLseqR#73]
Hello,

I am running into an issue with a dependency. I am seeing this error:

```
Counting SNPs in each window...
Calculating tricube smoothed delta SNP index...
Error in `h()`:
! Problem with `mutate()` input `tricubeDeltaSNP`.
✖ newsplit: out of vertex space
ℹ Input `tricubeDeltaSNP` is `tricubeStat(POS = POS, Stat = deltaSNP, windowSize, ...)`.
ℹ The error occurred in group 1: CHROM = "chr1".
Run `rlang::last_trace()` to see where the error occurred.
```

I believe this is an issue with R/locfit. I am unsure what to do at this point because I have filtered my dataset and changed window sizes. Basically every parameter that I can change, I have changed to no avail. 

I am trying to analyze a NIL in a reference genome background, so one bulk is all 0s. Do you think this is why?

Thank you.

**Comment by bmansfeld** [comment]
Hi,
Do the functions work with the trial data?
Did you try to increase the vertex space using the `maxk` parameter?
Let me know if these options still don't work we can do some tests and see if it something about your data type.

Ben

**Comment by mpaulsmeyer** [comment]
It seems to be working now? I reinstalled QTLseqr and it seems to be working now. Not sure why. R says it was the same image. Oh well. Thanks for the quick response.

**Comment by mpaulsmeyer** [comment]
I got the test data to work. It still gives me the same error with my data even when I filter down to 7K SNPs. I thought at first it might be a memory issue since it says "out of vertex space".

**Comment by bmansfeld** [comment]
that is strange. 
I just did a fresh install on our linux HPC and ran the trial set with out getting these issues. 
It's strange that it's doing it for the yang data for you. 
Maybe something with how your system is defining the memory. 
The locfit documents aren't great about explaining this error. Try increasing `maxk` and seeing if that works.

Ben

**Comment by mpaulsmeyer** [comment]
I apologize. The Yang data works. My data does not. 

I increased `maxk` for the `runQTLseqAnalysis()` function, and it worked. The G' analysis still does not work, unfortunately.

**Comment by mpaulsmeyer** [comment]
I have an additional question. What is the code for calculating the windows for the `nSNPs` option of `runQTLseqAnalysis()`? I like that graph and may actually publish that. I want to see the raw data for number of SNPs in a window. It may be in the plot, but I can't find it. Thank you.

**Comment by bmansfeld** [comment]
Ahh sorry I read that wrong. 
Ok well at least we understand now that it has something to do with the data size or type. 
Interesting that `maxk` doesn't work with `runGprime`. They both use the same locfit calculation in the background so I would imagine the windows and vertex space are the same??? 

As for nSNPs, there is a background C++ script that runs to calculate for each SNP how many SNPs are bracketing it within the set window size. This gets executed when you run any of the any of the mapping scripts ie `runQTLseqAnalysis`. It all gets added to the df in a column `nSNPs` so you can just use that column for plotting anything you want.

**Comment by mpaulsmeyer** [comment]
Thank you so much for your help. This is a great package that makes quality figures.
